[package]
name = "espanso-path"
version = "0.1.0"
authors = ["Federico Terzi <federico-terzi@users.noreply.github.com>"]
edition = "2021"

[dependencies]
log.workspace = true
dirs = "3.0.1"

[lints]
workspace = true
