name: espanso
version: 2.1.7-beta
summary: A Cross-platform Text Expander written in Rust
description: |
  espanso is a Cross-platform, Text Expander written in Rust.

  ## What is a Text Expander?

  A text expander is a program that detects when you type
  a specific keyword and replaces it with something else.
  This is useful in many ways:
  * Save a lot of typing, expanding common sentences.
  * Create system-wide code snippets.
  * Execute custom scripts
  * Use emojis like a pro.
  ___

  ## Key Features

  * Works on Windows, macOS and Linux
  * Works with almost any program
  * Works with Emojis ¯\_(ツ)_/¯
  * Works with Images
  * Includes a powerful Search Bar
  * Date expansion support
  * Custom scripts support
  * Shell commands support
  * Support Forms
  * App-specific configurations
  * Expandable with packages
  * Built-in package manager for espanso hub: https://hub.espanso.org/
  * File based configuration
  * Support Regex triggers
  * Experimental Wayland support (currently not available through Snap, visit the website for more info).

  ## Get Started

  Visit the official documentation: https://espanso.org/docs/

  ## Support

  If you need some help to setup espanso, want to ask a question or simply get involved
  in the community, Join the official Subreddit: https://www.reddit.com/r/espanso/

confinement: classic
base: core18

parts:
  espanso:
    plugin: rust
    source: .
    build-packages:
     - libssl-dev
     - libdbus-1-dev
     - libwxgtk3.0-gtk3-dev
     - pkg-config
     - libxkbcommon-dev
     - libxtst-dev
     - libx11-dev
    stage-packages:
     - libx11-6
     - libxau6
     - libxcb1
     - libxdmcp6
     - libxext6
     - libxinerama1
     - libxkbcommon0
     - libxtst6
     - libnotify-bin
     - libdbus-1-3
     - libssl1.1
     - libwxbase3.0-0v5
     - libwxgtk3.0-0v5
     - libatk-bridge2.0-0
     - libatspi2.0-0
     - libcairo-gobject2
     - libepoxy0
     - libgtk-3-0
     - libwayland-client0
     - libwayland-cursor0
     - libwayland-egl1
     - libwxgtk3.0-gtk3-0v5
     - xclip

apps:
  espanso:
    command: bin/espanso
